---
- hosts: localhost
  pre_tasks:
    - name: Localhost | Localhost Tasks
      become: True
      vars:
        ansible_become_pass: "{{ become_local }}"
      import_tasks: tasks/localhost.yml
      tags:
        - localhost

  roles:
    - name: ssh_copy_id
      tags: 
        - ssh
        - ssh_copy_id
        - localhost

- hosts: asir
  become: true
  pre_tasks:
    - name: Asir Deploy | Create Users
      import_tasks: tasks/users.yml
      tags: 
        - users

    - name: Asir Deploy | Install Packages
      import_tasks: tasks/install.yml
      tags:
        - install

    - name: Asir Deploy | Docker
      import_tasks: tasks/docker.yml
      tags:
        - docker

    - name: Asir Deploy | IAWE 
      import_tasks: tasks/iawe.yml
      tags:
        - iawe
    
    - name: Asir Deploy | BBDD
      import_tasks: tasks/bbdd.yml
      tags:
        - bbdd

    - name: Asir Deploy | Veyon
      import_tasks: tasks/veyon.yml
      tags:
        - veyon

  roles:
    - name: vbox_role
      tags:
        - vbox

