---
- hosts: asir
  tasks:
    - name: Create users and deleted users
      become: True
      import_tasks: tasks/users.yml
      tags: 
        - users

    - name: INSTALL
      become: true 
      import_tasks: tasks/install.yml
      tags:
        - install