---
#- hosts: localhost
#  gather_facts: false
#  vars:
#    ansible_become_pass: "{{ become_pass_local }}"
#  become: true
#  pre_tasks:
#    - name: Localhost | Localhost Tasks
#      import_tasks: tasks/localhost.yml
#      tags:
#        - localhost

  #roles:
  #  - name: ssh_copy_id
  #    tags: 
  #      - ssh_copy_id
  #      - localhost

- hosts: asir
  vars:
    ansible_become_pass: "{{ become_password }}"
  become: true
  roles:
    - name: ssh_copy_id
      tags: 
        - ssh_copy_id
        - localhost
  tasks:
    - name: Asir Deploy | Create Users
      import_tasks: tasks/users.yml
      tags: 
        - users

    - name: Asir Deploy | Install Packages
      import_tasks: tasks/install.yml
      tags:
        - install
    
    - name: Asir Deploy | Create Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ asir_user }}"
        group: "{{ asir_user }}"
        mode: 0755
      loop: "{{ new_directories }}"
    
    - name: Asir Deploy | Copy Templates
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ templates }}"
      
    - name: Asir Deploy | VBox
      import_tasks: tasks/vbox.yml
      tags:
        - vbox
    
    - name: Asir Deploy | Docker
      import_tasks: tasks/docker.yml
      tags:
        - docker

    - name: Asir Deploy | IAWE 
      import_tasks: tasks/iawe.yml
      tags:
        - iawe
    
    - name: Asir Deploy | BBDD
      import_tasks: tasks/bbdd.yml
      tags:
        - bbdd

    - name: Asir Deploy | Veyon
      import_tasks: tasks/veyon.yml
      tags:
        - veyon
    
    - name: Asir Deploy | Poweroff host/s
      command: poweroff
      ignore_errors: true    