---

- name: BBDD | Pull MySQL Docker image
  docker_image:
    name: "{{ bbdd_name_container }}"
    tag: "{{ bbdd_tag_container }}"

- name: BBDD | Init Container MySQL
  docker_container:
    name: mysql-fernando
    image: "{{ bbdd_image_container }}"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root # it would be advisable to use an encrypted variable
