---
- name: BBDD | Pull MySQL Docker image
  docker_image:
    name: "{{ db_container.repo_container }}"
    repository: "{{ db_container.image }}"
    source: pull

- name: BBDD | Init MySQL Container
  docker_container:
    name: "{{ db_container.name }}"
    image: "{{ db_container.image }}"
    ports:
      - "{{ db_container.ports }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ env_pass }}"
    container_default_behavior: no_defaults
