---

- name: Docker | Check if Docker GPG Key is already added
  stat:
    path: /usr/share/keyrings/docker.gpg
  register: docker_gpg_key

- name: Docker | Add Docker GPG Key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg
  when: docker_gpg_key.stat.exists == False

- name: Docker | Add Docker Repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Docker | Update APT List
  apt:
    update_cache: yes

- name: Docker | Install Docker
  apt:
    name: 
      - docker-ce
      - docker-compose
    state: present

- name: Docker | Add Users to Docker Group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
