---
- name: IAWE | Create Directory for IAWE
  file:
    path: "{{ path_iawe_directory }}"
    state: directory
    owner: "{{ asir_user }}"
    group: "{{ asir_user }}"
    mode: 0755
  
- name: IAWE | Copy Dockerfile Template
  template:
    src: "{{ dockerfile_template.src }}"
    dest: "{{ dockerfile_template.dest }}"

- name: IAWE | Build Docker Image
  shell: "docker build -t {{ name_iawe_image }} ."
  args:
    chdir: "{{ path_iawe_directory }}"

- name: IAWE | Create Docker network
  docker_network:
    name: "{{ name_iawe_network }}"

- name: IAWE | Run MySQL container
  docker_container:
    name: "{{ name_iawe_db }}"
    state: present
    network_mode: "{{ name_iawe_network }}"
    detach: yes
    env:
      MYSQL_ROOT_PASSWORD: root
    image: mysql
    container_default_behavior: no_defaults

- name: IAWE | Run PhpMyAdmin container
  docker_container:
    name: phpmyadmin
    state: present
    network_mode: "{{ name_iawe_network }}"
    detach: yes
    env:
      PMA_HOST: "{{ name_iawe_db }}"
    image: phpmyadmin
    ports:
      - "8080:80"
    container_default_behavior: no_defaults

- name: IAWE | Run IAWE container
  docker_container:
    name: "{{ name_iawe_container }}"
    state: present
    network_mode: "{{ name_iawe_network }}"
    detach: yes
    image: "{{ name_iawe_image }}"
    volumes:
      - "{{ path_iawe_docker_volume }}"
    ports:
      - "8000:80"
    restart: yes
    container_default_behavior: no_defaults
