---

- name: Install Packages | Update APT list
  apt:
    update_cache: yes

- name: Install Packages | Remove lock file SNAP 
  file:
    path: /etc/apt/preferences.d/nosnap.pref
    state: absent

- name: Install Packages | Install APT packages
  apt:
    name: "{{ asir_apt_packages }}"
    state: present

- name: Install Packages | Install SNAP packages
  snap:
    name: "{{ asir_snap_packages }}"
    classic: true
    state: present
  when: asir_snap_packages is defined