---
# Task for update APT list
- name: Install Packages | Update APT list
  apt:
    update_cache: yes

# Task for Remove lock file for snap installer
- name: Install Packages | Remove lock file SNAP 
  file:
    path: /etc/apt/preferences.d/nosnap.pref
    state: absent

# Task for install APT packages
- name: Install Packages | Install APT packages
  apt:
    name: "{{ asir_apt_packages }}"
    state: present

# Task for install SNAP packages
- name: Install Packages | Install SNAP packages
  snap:
    name: "{{ asir_snap_packages }}"
    classic: true
    state: present
  when: asir_snap_packages is defined

# Tasks for download & install deb Packages
- name: Install Packages | Download .deb Packages
  become_user: "{{ asir_user }}"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ path_asir_home }}/{{ item.name }}.deb"
  loop: "{{ asir_deb_packages }}"
  when: asir_deb_packages is defined

- name: Install Packages | Install .deb Packages
  apt:
    deb: "{{ path_asir_home }}/{{ item.name }}.deb"
    state: present
  loop: "{{ asir_deb_packages }}"
  when: asir_deb_packages is defined

- name: Install Packages | Delete .deb Packages
  file:
    path: "{{ path_asir_home }}/{{ item.name }}.deb"
    state: absent
  loop: "{{ asir_deb_packages }}"
  when: asir_deb_packages is defined

# Tasks for copy & install custom deb Packages
- name: Install Packages | Copy custom .deb Packages
  copy: 
    src: "{{ item.src }}"
    dest: "{{ path_asir_home }}/{{ item.name }}.deb"
  loop: "{{ asir_custom_packages }}"
  when: asir_custom_packages is defined

- name: Install Packages | Install custom .deb Packages
  apt:
    deb: "{{ path_asir_home }}/{{ item.name }}.deb"
    state: present
  loop: "{{ asir_custom_packages }}"
  when: asir_custom_packages is defined

- name: Install Packages | Delete custom .deb Packages
  file:
    path: "{{ path_asir_home }}/{{ item.name }}.deb"
    state: absent
  loop: "{{ asir_custom_packages }}"
  when: asir_custom_packages is defined