---

- name: Install Packages | Update apt list
  apt:
    update_cache: yes

- name: Install Packages | Install apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ asir_apt_packages }}"

#- name: Install Packages | Install snap packages
#  snap:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - "{{ asir_snap_packages }}"