---
- name: Localhost | Create .ssh Directory if not exists
  file:
    path: "{{ ssh_key.dir }}"
    state: directory
    mode: 0700

- name: Localhost | Generate SSH Key
  openssh_keypair:
    path: "{{ ssh_key.path }}"
    size: 3072
    type: rsa
    state: present
  ignore_errors: true

# Need veyon installed

- name: Localhost | Generate Veyon Key
  command: "veyon-cli authkeys create {{ veyon_key.name }}"
  register: veyon_gen_key
  ignore_errors: true
  tags: veyon

- name: Localhost | SetAccessGroup Veyon Key
  command: "veyon-cli authkeys setaccessgroup {{ veyon_key.name }}/public $USER && veyon-cli authkeys setaccessgroup {{ veyon_key.name }}/private $USER"
  when: veyon_gen_key.rc == 0
  tags: veyon

- name: Localhost | Export Veyon Key
  command: "veyon-cli authkeys export {{ veyon_key.name }}/public {{ veyon_key.src }}"
  when: veyon_gen_key.rc == 0
  tags: veyon

- name: Localhost | Add Veyon location 
  command: veyon-cli networkobjects add location "{{ veyon_key.name }}"
  register: veyon_location_check
  ignore_errors: true
  tags: veyon

- name: Localhost | Add Veyon computers
  command: veyon-cli networkobjects add computer "asir{{ ansible_loop.index }}" "{{ item }}" "" "{{ veyon_key.name }}"
  loop: "{{ hosts_deploy }}"
  loop_control:
    extended: true
  when: veyon_location_check.rc == 0
  tags: veyon
