---

- name: ASIR-DEPLOY | Copy Daemon script
  template:
    src: asir-deploy.service.j2
    dest: /etc/systemd/system/asir-deploy.service
    mode: 0644
    owner: root
    group: root
  notify: restart asir-deploy
  tags:
    - asir-deploy_service

- name: ASIR-DEPLOY | Configuring service
  systemd:
    name: asir-deploy
    state: "{{ asir-deploy_service_state }}"
    enabled: "{{ asir-deploy_service_enabled }}"
    daemon_reload: yes
  tags:
    - asir-deploy_service
