---

- name: Check if user {{ asir_user }} exists
  become: true
  ignore_errors: true
  command: id "{{ asir_user }}"
  register: result_asir_user

- name: "Create user {{ asir_user }}"
  user:
    name: "{{ asir_user }}"
    password: "{{ password_user | password_hash('sha512') }}"
    state: present
    createhome: yes
    shell: /bin/bash
  when: result_asir_user.rc != 0

- name: Check if user {{ asir_root_user }} exists
  become: true
  ignore_errors: true
  command: id "{{ asir_root_user }}"
  register: result_asir_root_user

- name: "Create user {{ asir_root_user }}"
  user:
    name: "{{ asir_root_user }}"
    groups: sudo
    password: "{{ password_root_user | password_hash('sha512') }}"
    state: present
    createhome: yes
    shell: /bin/bash
  when: result_asir_root_user.rc != 0

