---
- name: Veyon | Download Veyon Package
  become_user: "{{ asir_user }}"
  get_url:
    url: "{{ veyon_options.url }}"
    dest: "{{ veyon_options.path }}"

- name: Veyon | Install Veyon Package
  apt:
    deb: "{{ veyon_options.path }}"
    state: present

- name: Veyon | Delete Veyon Package
  file:
    path: "{{ veyon_options.path }}"
    state: absent

- name: Veyon | Create Veyon Directory
  file:
    path: "{{ veyon_directory_key }}"
    state: directory

- name: Veyon | Copy Veyon Key
  copy:
    src: "{{ veyon_key.src }}"
    dest: "{{ veyon_key.dest }}"

- name: Veyon | Change Authentication Mode
  shell: veyon-cli config set Authentication/Method 1

- name: Veyon | Import Veyon Key
  shell: veyon-cli authkeys import "{{ veyon_key.name }}"/public ./"{{ veyon_key.key }}"
  args:
    chdir: "{{ veyon_directory_key }}"
  ignore_errors: True

- name: Veyon | Start Veyon Service
  service:
    name: veyon
    state: started
    enabled: yes



