---
- name: Veyon | Add Veyon Repository
  apt_repository:
    repo: "deb https://github.com/veyon/veyon/releases/download/v4.8.0/veyon_4.8.0.0-ubuntu.jammy_amd64.deb"
    state: present
    update_cache: yes

- name: Veyon | Install Veyon
  apt:
    name: veyon
    state: present