---
- name: Veyon | Create Veyon Directory
  file:
    path: "{{ veyon_key.dir }}"
    state: directory

- name: Veyon | Copy Veyon Key
  copy:
    src: "{{ veyon_key.src }}"
    dest: "{{ veyon_key.dest }}"

- name: Veyon | Change Authentication Mode
  shell: veyon-cli config set Authentication/Method 1

- name: Veyon | Import Veyon Key
  shell: veyon-cli authkeys import "{{ veyon_key.name }}"/public ./"{{ veyon_key.key }}"
  args:
    chdir: "{{ veyon_key.dir }}"
  ignore_errors: True

- name: Veyon | Start Veyon Service
  service:
    name: veyon
    state: started
    enabled: yes



