---

- name: VMs | Create Directory
  file:
    path: "{{ path_images_iso }}"
    state: directory
    owner: "{{ asir_user }}"
    group: "{{ asir_user }}"
    mode: 0755

- name: VMs | Download Images ISO
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.path }}"
  with_items:
    - "{{ images_iso }}"

- name: VMs | Copy custom images
  template:
    src: "templates/{{ item }}"
    dest: "/path/to/destination/{{ item }}"
  with_items: "{{ path_custom_images }}"
  when: path_custom_images is defined

