---
## General

ansible_user: javiersb

asir_user: alumno
asir_root_user: profesor

## VMs

path_images_iso: /home/{{ asir_user }}/imagesISO
vm_type_os: Ubuntu_64
url_ubuntu_server: http://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso # v22.04
url_linux_mint: https://mirror.airenetworks.es/linuxmint/iso/stable/21/linuxmint-21-mate-64bit.iso # v21
  # Another options ( Spain Servers Only )
  # https://ftp.cixug.es/mint/stable/21/linuxmint-21-mate-64bit.iso
  # https://mirror.airenetworks.es/linuxmint/iso/stable/21/linuxmint-21-cinnamon-64bit.iso
  # https://ftp.cixug.es/mint/stable/21/linuxmint-21-cinnamon-64bit.iso
images_iso:
  - {name: ubuntuserver-22.04.iso, url: "{{ url_ubuntu_server }}", path: "{{ path_images_iso }}/{{ name }}"}
  - {name: linuxmint-21.iso, url: "{{ url_linux_mint }}", path: "{{ path_images_iso }}/{{ name }}"}

## IAWE

path_iawe_directory: "/home/{{ asir_user }}/iawe"
path_iawe_docker_volume: "{{ path_iawe_directory }}:/var/www/html"

## BBDD

bbdd_name_container: fernandorodriguezmoron/mysql
bbdd_tag_container: latest
bbdd_image_container: "{{ bbdd_name_container }}:{{ bbdd_tag_container }}"

bbdd_vm_name: bbdd_ubuntuserver
