---
## General

# User make the deploy - SSH User
ansible_user: "{{ asir_root_user }}" 

# User make the deploy - localhost
local_user: javiersb

# Target hosts for deploy - 
hosts_deploy:
  -

# Privileged user for Target hosts
asir_root_user: profesor

# Default user for Asir Deploy and Default path
asir_user: alumno
path_asir_home: "/home/{{ asir_user }}"

#Custom users
custom_users:
  - {name: curso}
  #- {name: example, password: "{{ example_password | password_hash('sha512') }}"}

# Vars for ssh-copy-id role
hostnames: "{{ hosts_deploy }}"
username: "{{ asir_root_user }}"
password: "{{ become_password }}"
ssh_public_key: "{{ ssh_key.path }}.pub"
#port: 22 --> default

# Template for Dockerfile
dockerfile_template: {src: templates/Dockerfile.bin.j2, dest: "{{ path_iawe_directory }}/Dockerfile"}
# template_example: {src: templates/example.j2, dest: "{{ path_example }}/example.example"}

