---
## General

ansible_user: profesor

asir_user: alumno
asir_root_user: profesor

path_asir_home: "/home/{{ asir_user }}"

## VBox

path_images_iso: "{{ path_asir_home }}/imagesISO"
#custom_images: # defined for add custom_images
# - /path/example
# - /path/example2

url_ubuntu_server: http://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso # v22.04
url_linux_mint: https://ftp.cixug.es/mint/stable/21.1/linuxmint-21.1-mate-64bit.iso # v21.1
  # Another options ( Spain Servers Only )
  # linux mint v21
  # https://ftp.cixug.es/mint/stable/21/linuxmint-21-mate-64bit.iso
  # https://mirror.airenetworks.es/linuxmint/iso/stable/21/linuxmint-21-cinnamon-64bit.iso
  # https://ftp.cixug.es/mint/stable/21/linuxmint-21-cinnamon-64bit.iso
  # https://mirror.airenetworks.es/linuxmint/iso/stable/21/linuxmint-21-mate-64bit.iso
  # https://ftp.cixug.es/mint/stable/21.1/linuxmint-21.1-mate-64bit.iso
  # https://mirror.crexio.com/linuxmint/isos/stable/21.1/linuxmint-21.1-cinnamon-64bit.iso

ubuntu_iso: {name: ubuntuserver-22.04.iso, url: "{{ url_ubuntu_server }}", path: "{{ path_images_iso }}/ubuntuserver-22.04.iso"}
linuxmint_iso: {name: linuxmint-21.1.iso, url: "{{ url_linux_mint }}", path: "{{ path_images_iso }}/linuxmint-21.1.iso"}
images_iso:
  - "{{ ubuntu_iso }}"
  - "{{ linuxmint_iso }}"

# values vms default
default_path_vms: "{{ path_asir_home }}/.VMsDisks"
default_bridgeadapter: enp0s3
default_hdd_format: VDI
default_net_type: bridged
default_memory_vram: 128 # MB

vm_options:
  - "{{ vm_ubuntu_options }}"
  - "{{ vm_linuxmint_options }}"

#values vm us2204
vm_ubuntu_options: {name: UbuntuServer22-04,ram: 2048,cpus: 2,disk_size: 20480,disk_path: "{{ default_path_vms }}/UbuntuServer22-04"}
#values vm lm21.1
vm_linuxmint_options: {name: LinuxMint21-1,ram: 4096,cpus: 3,disk_size: 30720, disk_path: "{{ default_path_vms }}/LinuxMint21-1"}

## IAWE

path_iawe_directory: "/home/{{ asir_user }}/iawe"
path_iawe_docker_volume: "{{ path_iawe_directory }}:/var/www/html"
name_iawe_image: iawe_image
name_iawe_container: iawe_php # Container with Apache and PHP
name_iawe_network: iawe_net
name_iawe_db: iawe_db

## BBDD

bbdd_name_container: fernandorodriguezmoron/mysql
bbdd_tag_container: latest
bbdd_image_container: "{{ bbdd_name_container }}:{{ bbdd_tag_container }}"

bbdd_vm_name: bbdd_ubuntuserver

## veyon

veyon_repo: https://github.com/veyon/veyon/releases/download/v4.8.0/veyon_4.8.0.0-ubuntu.jammy_amd64.deb