---
## General

ansible_user: profesor

asir_user: alumno
asir_root_user: profesor

## VMs

path_images_iso: /home/{{ asir_user }}/imagesISO
path_custom_images: 
vm_type_os: Ubuntu_64
url_ubuntu_server: http://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso # v22.04
url_linux_mint: https://ftp.cixug.es/mint/stable/21.1/linuxmint-21.1-mate-64bit.iso # v21.1
  # Another options ( Spain Servers Only )
  # linux mint v21
  # https://ftp.cixug.es/mint/stable/21/linuxmint-21-mate-64bit.iso
  # https://mirror.airenetworks.es/linuxmint/iso/stable/21/linuxmint-21-cinnamon-64bit.iso
  # https://ftp.cixug.es/mint/stable/21/linuxmint-21-cinnamon-64bit.iso
  # https://mirror.airenetworks.es/linuxmint/iso/stable/21/linuxmint-21-mate-64bit.iso
  # https://ftp.cixug.es/mint/stable/21.1/linuxmint-21.1-mate-64bit.iso
  # https://mirror.crexio.com/linuxmint/isos/stable/21.1/linuxmint-21.1-cinnamon-64bit.iso
images_iso:
  - {name: ubuntuserver-22.04.iso, url: "{{ url_ubuntu_server }}", path: "{{ path_images_iso }}/ubuntuserver-22.04.iso"}
  - {name: linuxmint-21.1.iso, url: "{{ url_linux_mint }}", path: "{{ path_images_iso }}/linuxmint-21.1.iso"}

## IAWE

path_iawe_directory: "/home/{{ asir_user }}/iawe"
path_iawe_docker_volume: "{{ path_iawe_directory }}:/var/www/html"
name_iawe_image: iawe_image
name_iawe_container: iawe_php # Container with Apache and PHP
name_iawe_network: iawe_net
name_iawe_db: iawe_db

## BBDD

bbdd_name_container: fernandorodriguezmoron/mysql
bbdd_tag_container: latest
bbdd_image_container: "{{ bbdd_name_container }}:{{ bbdd_tag_container }}"

bbdd_vm_name: bbdd_ubuntuserver
