---

## APT Packages
asir_apt_packages:
  # general
  - snapd
  - ubuntu-restricted-extras
  - rsync
  - build-essential
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - gnupg
  # dev
  - python3
  - python3-pip
  # utils
  - unrar
  - rar
  - cifs-utils
  # editors
  - nano
  - gedit
  - vim
  # internet
  - firefox
  # security
  - ssh
  # network
  - filezilla
  - whois
  - smbclient
  - telnet
  - nfs-common
  - net-tools
  - iputils-ping
  - traceroute
  - dnsutils
  - nmap
  - libwww-perl
  # ofimatic
  - inkscape
  - krita
  - libreoffice
  - libreoffice-l10n-es
  - mythes-es
  - hunspell-es
  # image and sound
  - kazam
  - audacity
  - obs-studio
  - vlc
  - blender
  - pinta
  - imagemagick
  - darktable
  - gimp
  - kdenlive
  - shutter
  # hardware
  - i2c-tools
  - hardinfo
  - lshw
  - smartmontools
  - dosbox
  - xournal
  - kinfocenter
  - lm-sensors
  - sensors-applet
  - isomaster
  - bless
  - gparted
  # xor
  - apache2-utils
  - apache2-dev
  - curl
  - lynx
  - wget
  # programs
  #- virtualbox

# SNAP Packages
asir_snap_packages:
  - mysql-workbench-community
  - code
  - atom

# Chrome Package
chrome_deb_package: {name: chrome, url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb} #oficial

# .deb Packages
asir_deb_packages:
  - "{{ veyon_deb_package }}"
  - "{{ chrome_deb_package }}"

#asir_custom_packages:
#  - {name: discord, src: files/discord-0.0.27.deb}
