---

password_user: alumno2020
password_root_user: profesor2021

veyon_directory_key: /etc/veyon/.key

veyon_key: {
  name: asir,
  key: asir_public_key.pem,
  src: "~/asir_public_key.pem",
  dest: "{{ veyon_directory_key }}/asir_public_key.pem"
}

become_password: profesor2021