---
## VBox

path_images_iso: "{{ path_asir_home }}/imagesISO"

url_ubuntu_server: http://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso # v22.04
url_linux_mint: https://ftp.cixug.es/mint/stable/21.1/linuxmint-21.1-mate-64bit.iso # v21.1
 
 # Another options ( Spain Servers Only )
  # linux mint v21
  # https://ftp.cixug.es/mint/stable/21/linuxmint-21-mate-64bit.iso
  # https://mirror.airenetworks.es/linuxmint/iso/stable/21/linuxmint-21-mate-64bit.iso
  # https://ftp.cixug.es/mint/stable/21.1/linuxmint-21.1-mate-64bit.iso


ubuntu_iso: {name: ubuntuserver-22.04.iso, url: "{{ url_ubuntu_server }}", path: "{{ path_images_iso }}/ubuntuserver-22.04.iso"}
linuxmint_iso: {name: linuxmint-21.1.iso, url: "{{ url_linux_mint }}", path: "{{ path_images_iso }}/linuxmint-21.1.iso"}
images_iso:
  - "{{ ubuntu_iso }}"
  - "{{ linuxmint_iso }}"

#custom_images: # defined for add custom_images
# - example_iso: {name: example.iso, src: files/example.iso, dest: "{{ path_images_iso }}/example.iso"}

# values vms default
default_path_vms: "{{ path_asir_home }}/.VMsDisks"
default_bridgeadapter: enp0s3
default_hdd_format: VDI
default_net_type: bridged
default_memory_vram: 128 # MB

vm_options:
  - "{{ vm_ubuntu_options }}"
  - "{{ vm_linuxmint_options }}"

#values vm us2204
vm_ubuntu_options: {
  name: UbuntuServer22-04,
  ram: 2048,
  cpus: 2,
  disk_size: 20480,
  disk_path: "{{ default_path_vms }}/UbuntuServer22-04",
  iso_path: "{{ ubuntu_iso.path }}"
  }
#values vm lm21.1
vm_linuxmint_options: {
  name: LinuxMint21-1,
  ram: 4096,
  cpus: 3,
  disk_size: 30720,
  disk_path: "{{ default_path_vms }}/LinuxMint21-1",
  iso_path: "{{ linuxmint_iso.path }}"
  }

#values vm kali

#https://cdimage.kali.org/kali-2023.2/kali-linux-2023.2-virtualbox-amd64.7z oficial
#https://sourceforge.net/projects/osboxes/files/v/vb/25-Kl-l-x/2022.3/64bit.7z/download
#Username: osboxes
#Password: osboxes.org
#Guest Additions: Installed
#Keyboard Layout: US (Qwerty)

#values vm metasploitable

#https://download.vulnhub.com/metasploitable/metasploitable-linux-2.0.0.zip
#unzip
#Metasploitable2-Linux/Metasploitable.vmdk